# Site
repository: sproogen/resume-theme
favicon: favicon.ico

# Personal info
name: Vikash Meghwal
title: Bachelor in Scince B.S. Chemistry
email: mevikash@iitk.ac.in
website: https://github.com/mevikash

# Social links
twitter_username: daneil_radcliff
github_username:  mevikash
# dribbble_username: jekyll
facebook_username: mevikashvira
# flickr_username: jekyll
instagram_username: meghwalvikash
linkedin_username: Vikash Meghwal
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Vikash Meghwal and I'm a First Year Undergraduate pursuing B.S. in Chemistry from Indian Institute of Technology, Kanpur (2019 - 2023)...

  I am skilled in: <mark>DNA</mark> and <mark>Paintings</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Learning and Teaching some of my other interests and hobbies are:
   - Art and Paintings
   - Chess
   - Cooking 
   - Curious about Creative work
   - Gaming 
   - Long Jump
   - Learning languages
   - Massage therapy
   - [Music](https://www.youtube.com/watch?v=rjWnxIefo1g)
   - Sleeping
   - Traveling
   - Yoga

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
